---
# tasks file for install_apache
- name: installed vsftpd
  yum: name=vsftpd state=latest

- name: enable vsftpd
  service: name=vsftpd state=started enabled=yes

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    zone: public
    port: 20/tcp
    permanent: yes
    state: enabled

- name: Generated vsftpd.conf file
  template: src=vsftpd.j2 dest={{destin_files}}

- name: create directory /var/ftp/pub 
  ansible.builtin.file:
    path: '{{ anon_path }}'
    state: directory
    mode: '0777'

- name: create directory /var/ftp/pub
  ansible.builtin.file:
    path: '{{ upload_path }}'
    state: directory
    mode: '0777'

- name: generate test file
  ansible.builtin.file:
    path: '{{ upload_path }}/test.txt'
    state: touch
    mode: '0777'

- name: opened ftp ports
  ansible.posix.firewalld:
    zone: public
    service: ftp
    permanent: yes
    state: enabled

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: vsftpd restarted
  ansible.builtin.service:
    name: vsftpd
    state: restarted
