- name: make sure the parameters are added to the grub
  hosts: test_servers
  become: yes

  tasks:

  - name: added options in grub
    lineinfile:
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX="'
#      search_string: '^GRUB_CMDLINE_LINUX="'
      insertafter: '^GRUB_CMDLINE_LINUX=" '
      state: present
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0 crashkernel=auto resume=/dev/mapper/cl-swap rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet"'

  - name:  grub config applied
    shell: grub2-mkconfig
