
---
- name: installed httpd created index.html and opened 80 and 443 / tcp ports
  hosts: test_servers
  become: yes
  

  vars:
    source_file: ./index.html
    destin_files: /var/www/html/

  tasks:

  - name: installed httpd
    yum: name=httpd state=latest

  - name: enable httpd
    service: name=httpd state=started enabled=yes

  - name: created index.html 
    copy: src={{ source_file }} dest={{destin_files}} mode=777

  - name: permit traffic in default zone for http service
    ansible.posix.firewalld:
      zone: public
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: opened 443 port
    ansible.posix.firewalld:      
      zone: public
      port: 443/tcp
      permanent: yes
      state: enabled

  - name: Reload firewalld
    systemd:
      name: firewalld
      state: reloaded
